### ISSUE TITLE
README.md Example compile Error

### ISSUE THREAD

**Issue by DeltaManiac** [AllenDang/gimu#2]
The simple demo example in the https://github.com/AllenDang/gimu/blob/master/README.md has the following compile error 
```
# command-line-arguments
./main.go:14:25: cannot use width (type int32) as type int in argument to image.Rect
./main.go:14:25: cannot use height (type int32) as type int in argument to image.Rect
./main.go:16:10: cannot use bounds (type image.Rectangle) as type nk.Rect in argument to w.Window
```
Changing 
```go
bounds := image.Rect(0, 0, width, height)
```
to 
```go
bounds := nk.NkRecti(0, 0, width, height)
```

Seems to solve the issue, but is this the right fix ?

Awesome Library BTW

**Comment by AllenDang** [comment]
@DeltaManiac Thanks! Yes, it's the right fix.
I used to think about to wrap all the constants from nk package. But now I think it's better to use them directly to make it easier to future upgrade with nuklear.
